// -*- mode: c++; -*-

#ifndef YPDF_DETAIL_CONFIG_HH
#define YPDF_DETAIL_CONFIG_HH

#include <ypdf/detail/_config.hh>

#define YPDF_PACKAGE PACKAGE
#define YPDF_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#define YPDF_PACKAGE_NAME PACKAGE_NAME
#define YPDF_PACKAGE_STRING PACKAGE_STRING
#define YPDF_PACKAGE_TARNAME PACKAGE_TARNAME
#define YPDF_PACKAGE_VERSION PACKAGE_VERSION
#define YPDF_VERSION VERSION

#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION

#endif // YPDF_DETAIL_CONFIG_HH
